scrape_configs:
  - job_name: nodes
    static_configs:
      - targets: ['demoexporter1:9100', 'demoexporter2:9200']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

rule_files:
  - "/etc/prometheus/rules.yml"